<?php
define("DOCUMENT_ROOT", $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR);
define("DIST", $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . "dist" . DIRECTORY_SEPARATOR);
define("DIST_PHP", $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . "dist" . DIRECTORY_SEPARATOR . "php" . DIRECTORY_SEPARATOR);
define("APPLICATION", $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . "application" . DIRECTORY_SEPARATOR);
define("CONFIGS", APPLICATION . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR);
define("CONTROLLERS", APPLICATION . DIRECTORY_SEPARATOR . "controllers" . DIRECTORY_SEPARATOR);
define("INCLUDES", APPLICATION . DIRECTORY_SEPARATOR . "includes" . DIRECTORY_SEPARATOR);
define("LOGS", APPLICATION . DIRECTORY_SEPARATOR . "logs" . DIRECTORY_SEPARATOR);

define("LINKEDIN_PROD", "78shltqcif7413");
define("FACEBOOK_PROD", "542086662642216");
define("GOOGLEPLUS_PROD", "365560908295-koghokncubaessn558tef8g0m0pb0ngm");

define("LINKEDIN_DEBUG", "78a31asbikx1we");
define("FACEBOOK_DEBUG", "782783395221875");
define("GOOGLEPLUS_DEBUG", "533618875435-maggrqm8nokmomk49bjtkhrstqk7f8r8");

define("SMTPSECURE", "tls");
define("HOSTSMTP", "smtp.sendgrid.net");
define("PORTSMTP", 587);
define("USERSMTP", "apikey");
define("PASSSMTP", "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");
define("SETFROMEMAILSMTP", "no-reply@pedela.com.br");
define("SETFROMNAMESMTP", "Pede Lá");
define("REPLYTOSMTP", "contato@pedela.com.br");